
export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',   
};

export const bookConstants = {
    REGISTER_BOOK_SUCCESS: 'BOOK_REGISTER_SUCCESS',

    EDIT_BOOK_SUCCESS: 'BOOK_EDIT_SUCCESS',

    FETCH_BOOK_SUCCESS: 'BOOK_FETCH_SUCCESS',
    
    DELETE_BOOK_SUCCESS: 'BOOK_DELETE_SUCCESS',
};