
export const userConstants = {
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',

    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',

    LOGOUT: 'USERS_LOGOUT',   
};

export const bookConstants = {
    REGISTER_BOOK_SUCCESS: 'BOOK_REGISTER_SUCCESS',

    EDIT_BOOK_SUCCESS: 'BOOK_EDIT_SUCCESS',

    FETCH_BOOK_SUCCESS: 'BOOK_FETCH_SUCCESS',
    
    DELETE_BOOK_SUCCESS: 'BOOK_DELETE_SUCCESS',
};